services:
  mysql:
    image: mysql:8.0
    container_name: home-inventory-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home_inventory
    volumes:
      - ~/.db/home-inventory/mysql:/var/lib/mysql
